apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-dev
  namespace: openshift-gitops  # <--- Namespace del operador
spec:
  project: default
  source:
    repoURL: 'https://github.com/panchoraposo/demo-cicd.git'  # <--- Repositorio Git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pacman-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # ArgoCD creará el namespace 'pacman-dev'